[package]
name = "qt"
version = "0.1.0"
authors = ["Jakob Botsch Nielsen <Jakob.botsch.nielsen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eqlog = { path = "eqlog" }
lazy_static = "1.4.0"

[build-dependencies]
lalrpop = "0.17.2"
